# Use the official Nginx image as the base image.
FROM nginx:latest

# Copy the custom Nginx configuration file to the container.
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

# Copy a custom startup script
COPY ./nginx/start-nginx.sh /start-nginx.sh

# Make the script executable
RUN chmod +x /start-nginx.sh

WORKDIR /app/web/staticfiles/

ENTRYPOINT ["/start-nginx.sh"]